### ISSUE TITLE
Doesn't play nice with jshint

### ISSUE THREAD

**Issue by jwhitmarsh** [ignism/nucleus-dark-ui#35] opened 2015-10-02 10:15 UTC
`.git-line-modified` is taking precedence over `.atom-jshint-error`

**Comment by ignism** [comment] 2015-10-02 12:26
Could you be more specific? Give an example on what you would expect it to do? I am not familiar with JSHint, but for me Nucleus Dark doesn't appear to be acting different to One Dark for instance.

**Comment by jwhitmarsh** [comment] 2015-10-02 12:35
The [atom-jshint](https://atom.io/packages/atom-jshint) package applies a `.atom-jshint-error` class which colors the line number red. Attached is a screenshot showing that the line number is having that color overloaded by other classes (one of which I've identified as `.git-line-modified`). 

![screen shot 2015-10-02 at 13 32 34](https://cloud.githubusercontent.com/assets/8026009/10246522/14202600-690a-11e5-9c2d-371c457cb0a4.png)

Here's a screenshot where I've altered the jshint package to apply that color with an `!important` flag, so the line number is colored correctly.

![screen shot 2015-10-02 at 13 34 33](https://cloud.githubusercontent.com/assets/8026009/10246570/6ad5aea2-690a-11e5-8efe-e40e2607a4aa.png)

**Comment by ignism** [comment] 2015-10-03 13:46
I really want to fix this, but I fail to reproduce the error. I made sure I have atom-jshint, and just installed jshint itself. But it doesn't seem to work for me. (the other JSHint package worked out of the box). Is there something I overlooked?

**Comment by jwhitmarsh** [comment] 2015-10-04 09:38
Huh, I wonder if it's the order I installed the packages in - I installed nucleas last. Does Atom work like that? I'll clear my packages and try again.

**Comment by ignism** [comment] 2015-10-05 14:17
I pushed a new patch, 0.5.13. Please tell me if it fixed your problem.

**Comment by ignism** [comment] 2015-10-07 08:27
Ok, got it to work for myself now. Seems to be fixed, closing the issue.

**Closed as completed by ignism** 2015-10-07 08:27 UTC
