### ISSUE TITLE
Support gutter highlighting

### ISSUE THREAD

**Issue by derekperkins** [ignism/nucleus-dark-ui#46] opened 2015-11-10 03:21 UTC
A lot of packages use gutter highlighting for notifications, but those are just ignored in nucleus. Otherwise, this is hands down my favorite theme.
https://github.com/atom/decoration-example

**Comment by ignism** [comment] 2015-11-13 23:41
It's not that they are ignored, but they are likely overridden. I need to look into this.

**Comment by derekperkins** [comment] 2015-11-14 01:36
The built in `git` highlighting works fine, but specifically https://atom.io/packages/go-plus doesn't show when there is build error. I've tried this package with about a dozen other themes that all showed highlighting on the row number. Here's an example:

#### nucleus-dark-ui

![image](https://cloud.githubusercontent.com/assets/3588778/11161269/5ff76222-8a35-11e5-850c-1da749834558.png)

#### atom dark

![image](https://cloud.githubusercontent.com/assets/3588778/11161260/22e2d31c-8a35-11e5-8f06-d4e01ad68c90.png)

**Comment by ignism** [comment] 2015-11-16 16:35
That decoration-example package looks neat, but I can't install it. Besides go-plus (i'm not familiar with it, and installing it seems a hassle) are there other packages that have the same issue for you?

**Comment by ignism** [comment] 2015-12-01 16:08
I probably found a fix, please let me know if patch 0.6.13 does the trick for you.

**Comment by derekperkins** [comment] 2015-12-02 02:08
It didn't appear to change anything for me.

**Comment by michaeltrobinson** [comment] 2015-12-23 21:15
I'm having the same issue with the `go-plus` package. Anything I can do to help?

**Comment by ignism** [comment] 2016-09-24 13:01
Should be fixed as of 0.10.0, unable to reproduce.

**Closed as completed by ignism** 2016-09-24 13:01 UTC
Labels: help wanted
