### ISSUE TITLE
selector color problem in nucleus

### ISSUE THREAD

**Issue by cocody** [ignism/nucleus-dark-ui#81] opened 2016-09-30 08:48 UTC
I'm very love this UI theme. But it break my heart for me in the last release.

![](http://ww4.sinaimg.cn/large/71b8a169gw1f8bpftqo1tj20ig0gcac7.jpg)

**Comment by ignism** [comment] 2016-09-30 08:50
will fix this today! Please don't leave us Nukers!

**Comment by nblake989** [comment] 2016-09-30 20:36
Latest update to `0.10.7` broke colors in the fuzzy finder:
![screen shot 2016-09-30 at 1 34 09 pm](https://cloud.githubusercontent.com/assets/8633545/19006067/afbd91ac-8712-11e6-97b2-7d0d8e47deda.png)

I can no longer see any of the filenames in the fuzzy finder tool.

**Comment by ignism** [comment] 2016-10-01 11:40
Hmm I cant seem to reproduce this error. What packages do you have installed? I see some I don't recognize. OmniSearch? I can then stylize that package.

On a side note, what package is the FileTree SourceControl tabs? And I would love to have that open files package too :D

**Comment by npatmaja** [comment] 2016-10-02 02:42
Same problem with @cocody, it seems the latest update broke colors in [advanced-open-file](https://github.com/Osmose/advanced-open-file) package.

![screen shot 2016-10-02 at 09 37 14](https://cloud.githubusercontent.com/assets/967979/19018245/76fe2408-8884-11e6-9dee-a1f0a5ed3a5a.png)

**Comment by ignism** [comment] 2016-10-02 15:55
I fixed the advanced-open-file issue, though it is not related to @cocody's reall. Thing is, I'd like to change the style of git:control's overlay to have it look more consitent. But haven't found a good solution yet.

**Comment by ignism** [comment] 2016-10-02 17:30
The main issue with git:control is fixed now. @nblake989  Could you get back to me about the packages you use in the screenshot?

**Comment by ignism** [comment] 2016-10-03 09:06
@nblake989 I found out that it is the nuclide package that is causing trouble. I am closing this issue now, because its unrelated.

**Comment by cloudkite** [comment] 2016-10-04 20:47
@ignism any plans to support nuclide?

It works perfectly with nuclide in 0.9.5, so I'm going to hold off updating for now

**Comment by cloudkite** [comment] 2016-10-04 20:51
having said that understand if its not a priority. happy to just sit on 0.9.5 :D

**Comment by ignism** [comment] 2016-10-04 21:31
actually I look into it what needs fixing.

**Comment by cocody** [comment] 2016-10-08 04:41
In version `0.10.9` 

**Contrast is too shallow**

![](http://ww3.sinaimg.cn/large/71b8a169gw1f8kradrmiwj20fb045q3l.jpg)
![](http://ww1.sinaimg.cn/large/71b8a169gw1f8krayeqlmj20ah06wt96.jpg)


![](http://ww1.sinaimg.cn/large/71b8a169gw1f8krcloidzj20oy06hq3j.jpg)
![](http://ww1.sinaimg.cn/large/71b8a169gw1f8krcw8z6vj20o20733yx.jpg)

**Comment by ignism** [comment] 2016-10-08 13:46
the first screenshot, which package is that? could you identify that for me?

**Comment by cocody** [comment] 2016-10-08 17:10
@ignism en..It should be `atom-ternjs` or `autocomplete-` in `Core Packages`. Take off some `background` and take the Contrast heigher, I think it will be better

**Comment by nblake989** [comment] 2016-10-08 17:20
In the first screenshot it was Nuclide that add the source control and FuzzyFinder search enhancement.

**Comment by ignism** [comment] 2016-10-08 18:31
So I am at the point of dropping the light overlay color alltogether... at least, I'm thinking about it.

**Comment by ignism** [comment] 2016-10-09 11:08
How does patch 0.10.10 work for you guys?

**Comment by lironess** [comment] 2016-10-09 12:34
[reference to my comment about 0.10.10 fix](https://github.com/ignism/nucleus-dark-ui/issues/82#issuecomment-252483928)

**Comment by ignism** [comment] 2016-10-12 09:10
How's 0.10.11 for you @cocody ?

**Closed** 2016-11-30 12:11 UTC
